baseURL = "https://clair.eth.link"

title = "Axiom A Hugo Theme"
languageCode = "en-us"
defaultContentLanguage = "en-us"

theme = "axiom"

canonifyURLs = false
rssLimit = 100
enableEmoji = true
summaryLength = 40
enableRobotsTXT = true
pluralizelisttitles = false
footnoteReturnLinkContents = "&#8617;"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
post = "/:filename"

[params]
mainSections = ["post"]
copyrightYear = 2020

[params.services]
analyticsId = "UA-DEV"
adwordsId = "AW-DEV"
adsenseId = "CA-PUB-DEV"
adsenseAdSlotId = "ID-DEV"
adsenseLazy = false
adwordsConversionId = "ID-DEV"
adwordsConversionValue = 0
facebookApp = "FB-DEV"
facebookPixel = "FB-DEV"
disqusUser = "na"

[params.path]
image = "image/"
video = "video/"
author = "image/author/"
brand = "image/brand/"
font = "font/"
pdf = "pdf/"

[params.cdn]
provider = "local"
type = "image"

[params.cloudinary]
host = "https://res.cloudinary.com/CLOUD_NAME/"
version = ""
image = "image/upload/"
raw = "raw/upload/"
video = "video/upload/"

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[params.img]
width = "2048"
height = "1024"
default = "chardon.jpg"

[params.font]
type = ""
files = []

[params.brand]
domain = "example.com"
email = "info@example.com"
github = "example"
facebook = "example"
twitter = "example"
instagram = "example"
youtube = "example"
pinterest = "example"
linkedin = "example"
stacko = "10101010"
faviconIco = "favicon.ico"
faviconAlt = "favicon.ico"
icon1To1 = "chardon.jpg"
icon2To1 = "chardon.jpg"
logo = "chardon.jpg"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
autoHeadingID = false
[markup.highlight]
codeFences = false
noClasses = false
tabWidth = 2

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.mobile]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.mobile]]
url = "/about/"
name = "About"
weight = 2

[[menu.foot]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/about/"
name = "About"
weight = 2

[languages]
[languages."en-us"]
weight = 1
languageName = "US English"
